FROM jenkins/jenkins:lts

USER root

# Copy docker CLI
COPY --from=docker:27-cli /usr/local/bin/docker /usr/local/bin/docker

# Install docker compose standalone binary
RUN curl -L https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64 \
    -o /usr/local/bin/docker-compose && \
    chmod +x /usr/local/bin/docker-compose

USER jenkins