-- AlterTable
ALTER TABLE "Project"
ADD COLUMN "description" TEXT,
ADD COLUMN "region" TEXT NOT NULL DEFAULT 'US-EAST-1',
ADD COLUMN "status" TEXT NOT NULL DEFAULT 'ACTIVE';

-- AlterTable
ALTER TABLE "Service"
ADD COLUMN "status" TEXT NOT NULL DEFAULT 'ACTIVE',
ADD COLUMN "uptime" DOUBLE PRECISION NOT NULL DEFAULT 100;
